### PR TITLE
adding QBO diagnostics

### PR DESCRIPTION
**Pull request by islasimpson**
This script plots time series of 5S-5N zonal mean zonal wind to examine the QBO.  It also plots the Dunkerton and Delisi QBO amplitude.  A couple of remaining issues...

(1) The line to point to the correct plot directory needs to be checked and un-commented and my temporary specification of the plot path removed.

(2) The titles aren't dealt with very well.  They will easily become overlapping with long run names.  I don't know if someone already has a better way to deal with this.

### CODE REVIEW

**Comment by nusbaume** [comment]
@islasimpson Thanks for the QBO diagnostics!  How would you like to proceed on the relevant code modifications to your PR?  I can either just post the recommended code changes here and have you implement them yourself, or I can push the code changes directly to your branch (but this would require you not working on your branch until I have finished).  Just let me know if you have a preference!

**Comment by islasimpson** [comment]
@nusbaume Happy to do whatever is normal - I won't be working on the branch, so I think either way will work.  Thanks.

**Comment by nusbaume** [comment]
@islasimpson Sounds good.  I'll go ahead and do a review with the relevant code change requests posted.   However, if you find you are unable to implement them for any reason just let me know and I can take over.

**Review by nusbaume — CHANGES_REQUESTED** [review]
@islasimpson This looks good, but I did have some (hopefully easy to implement) change requests.  Of course if you have any questions or concerns with my requests just let me know.  

Also, once the code changes are made then I'll go ahead and perform some tests, and if everything works we'll get this PR merged.  Thanks!

**Review by nusbaume — APPROVED** [review]
All tests passed (with a few minor bug fixes), so this PR is good to go.  Thanks @islasimpson!

**Pull request merged**
