### PR TITLE
Added capability to run CVDP from within ADF

### LINKED ISSUE #17: Incorporate the CVDP into the diagnostics framework
Try calling the CVDP using the CAM diagnostics framework.  This will provide an initial test for how easy/hard it is to incorporate external diagnostics packages, and may provide a code base for further development of a unified diagnostics package.

### LINKED ISSUE #77: File names of ADF-created timeseries should match the CESM timeseries file naming standard
ADF created timeseries should include the date range in the file names. At present, timeseries that are created are named:
$cam_case_name.ncrcat.$variable.nc
To allow users to know the dates within the file, to allow future CVDP integration, and as the ADF will likely be used to form timeseries files (as it's easier than other methods), I propose the files be named the same as standard CESM timeseries files:
$cam_case_name.h0.$variable.YYYYMM-YYYYMM.nc

### PR DESCRIPTION
**Pull request by phillips-ad**
Added capability to run CVDP from within ADF, and modified output ADF timeseries names to match CESM standards. 

The CVDP can now easily be called from within the ADF config YAML file. Every run specified in cam_case_name (for both diag_cam_climo and diag_cam_baseline_climo sets) will be analyzed and compared to the default stack of 4 sets of observations. The years that the user set to be analyzed (set via start_year and end_year) are what the CVDP will use. Observational datasets time periods are set to whatever the current default namelist_obs has in it. Currently with CVDP v5.2.0 two observational sets run from 1920-2018, and two run from 1979-2018. 

There are four CVDP settings within the config yaml file:
- cvdp_run. (true or false).  Setting this to true copies over the necessary CVDP code, sets up the necessary files, and submits the CVDP in the background. This allows the ADAF to proceed, but also means the CVDP will likely finish after the ADF is completed. 
- cvdp_codebase_loc. This is the directory path where the CVDP codebase is located. 
- cvdp_loc. This is where the CVDP directory will be created for use by the ADF. The CVDP code will be copied from cvdp_codebase_loc to this location, and the following files will be automatically modified: driver.ncl and namelist. 
- cvdp_tar. (true or false). Setting this to true will result in all CVDP output being tarred up.

CVDP output will be placed in cvdp_loc/$case_name[0]/output.

In order to allow the CVDP to be called from the ADF, the ADF now creates timeseries (from history files) whose names end in "YYYYMM-YYYYMM.nc". Altering the timeseries naming in this way brings the ADF created timeseries up to the current CESM naming standard.

Fixes #17 
Fixes #77

### CODE REVIEW

**Comment by nusbaume** [comment]
@phillips-ad Thank you so much for doing this!  It looks like there are a few minor code mods that will need to be made.  I can either just make them myself and push it to your branch (which will automatically update this Pull Request), or I can send you the list of changes and you can implement them yourself.  Just let me know which way you prefer!

**Comment by phillips-ad** [comment]
@nusbaume If you are OK making the minor changes yourself that's fine with me! I will update my original comment on this pull request to be much more descriptive of what I did. One matter that I wasn't sure how to address documentation wise: Users will have to load the NCL module on whatever system (CGD or CISL) they are on.

**Comment by nusbaume** [comment]
Sounds good!  I'll go ahead and make the mods along with any other fixes I find during testing (hopefully there aren't any, but you never know).  If all goes well I'll get these changes merged into the ADF early next week.

Also, thanks for the heads up about NCL!  I'll go ahead and update the relevant documentation once this PR is merged to let any future users know of the new requirement.

Finally, when you do update your original comment, can you change the issue references to be on their own separate lines, e.g.:

````
Fixes #17
Fixes #77 
````

Otherwise Github can have problems managing the issues properly.  Thanks!

**Review by nusbaume — APPROVED** [review]
@phillips-ad All of my testing is complete, so this PR is good to go.  Thanks again for implementing the CVDP!

**Pull request merged**
